name: Azure API Mgmt Deploy 
on: 
  push:
    branches:
      - main
    paths:
      - 'apim/**'

jobs:
  call-baseline-workflow-passing-data:
    name: 'Run'
    permissions:
      id-token: write 
      contents: read
    uses: ./.github/workflows/deploy-module-template.yml
    with:
      modulePath: 'apim/'
      rgName: 'rg-apim-video'
    secrets: inherit
