name: 'Bicep Unit Tests'

# We run on just PRs + main since this validate requires full read/write permissions to Azure and we can't do wildcards for the branch name in Azure OIDC federated credentials
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  LOCATION: 'eastus2'
  RG_NAME: 'rg-adf-devops'
  SA_NAME: 'saadfdevops'
  DF_NAME: 'adf-devops'
  KV_NAME: 'kv-devops'
  CONT_NAME: 'blobdevops'
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  
#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  bicep-unit-tests:
    name: 'Bicep Unit Tests'
    runs-on: ubuntu-latest
    # Bicep What-if / Validate functions also check if your role has permisisons to create the resources so we need full read/write permissions
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate to Az CLI using OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Checks that all Bicep configuration files adhere to a canonical format
    - name: 'Bicep Lint'
      uses: Azure/cli@v1
      with:
        inlineScript: az bicep build --file adf/main.bicep
        
    # Validate whether a template is valid at subscription scope
    - name: 'Bicep Validate'
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub validate \
            --name validate-${{ github.run_id }} \
            --template-file adf/main.bicep \
            --parameters rgName=$RG_NAME location=$LOCATION kvName=$KV_NAME containerName=$CONT_NAME saName=$SA_NAME dfName=$DF_NAME \
            --location $LOCATION

    # Perform a security scan of the bicep code using checkov
    - name: 'Run Checkov action'
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with: 
        framework: bicep
